In [2]:
import pandas as pd

1. Creating a Series
Create a pandas Series named movie_ratings. Use three movie titles as the index (e.g., 'Inception', 'Matrix', 'Interstellar'). The values should be scores from 1 to 10. Name the Series 'Scores'.

In [3]:
#1) 
movies_name = ['Inception', 'Matrix', 'Interstellar']
movies_score = [5, 8.9, 9]
movie_ratings = pd.Series(data=movies_score, index=movies_name, name='Scores')
print(movie_ratings)

Inception       5.0
Matrix          8.9
Interstellar    9.0
Name: Scores, dtype: float64

2. Creating a DataFrame
Create a DataFrame named employees. It must have three columns: Name, Age, and Salary. Make up data for 3 employees. Use the Name column as the index of the DataFrame.

In [77]:
#2)

employees = pd.DataFrame({'Name':['Arthur', 'Jhon', 'Brayan'], 'Age':[24, 34,27], 'Salary': ['$2400', '$2100', '$2600']}).set_index('Name')
print(employees)

        Age Salary
Name
Arthur   24  $2400
Jhon     34  $2100
Brayan   27  $2600

3. Selecting a Column
From the reviews DataFrame, select the taster_name column and save it to a variable called tasters.

In [13]:
taster_csv = pd.read_csv(r'c:\Users\donsh\OneDrive\Pictures\Desktop\Pandas\reviews_130k.csv', index_col=0,)

In [76]:
tasters = taster_csv['taster_name'] 
taster_csv.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,tax,country_winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,tasters,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN,Italy-Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,tasters,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,18.0,Portugal-Quinta dos Avidagos
2,no_designation,no_designation,no_designation,no_designation,NaN,no_designation,no_designation,no_designation,no_designation,no_designation,no_designation,no_designation,no_designation,NaN,no_designation-no_designation
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,tasters,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,15.6,US-St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,tasters,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,78.0,US-Sweet Cheeks

4. Using .loc (label-based)
Using .loc, extract the value of the winery column for the wine at index 5.

In [17]:
taster_csv.loc[4, 'winery']

'Sweet Cheeks'

5. Using .iloc (position-based)
Using .iloc, extract the very first value in the entire reviews DataFrame (first row, first column).

In [21]:
taster_csv.iloc[:1]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,tasters,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia

6. Conditional Selection (AND)
Filter the reviews DataFrame to show only wines from 'Germany' where the price is greater than 50.

In [26]:
taster_csv.loc[taster_csv.country.isin(['Germany']) & (taster_csv.price >= 50)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
347,Germany,"Dusty, saffron-spiced earthiness is juxtaposed...",Kiedrich Gräfenberg Trockenbeerenauslese,97,775.0,Rheingau,NaN,NaN,tasters,NaN,Robert Weil 2014 Kiedrich Gräfenberg Trockenbe...,Riesling,Robert Weil
354,Germany,"Whiffs of white mushroom, saffron and caramel ...",Kiedrich Gräfenberg Beerenauslese,96,365.0,Rheingau,NaN,NaN,tasters,NaN,Robert Weil 2014 Kiedrich Gräfenberg Beerenaus...,Riesling,Robert Weil
358,Germany,"Intensely fragrant, this honey-sweet auslese w...",Hattenheimer Hassel Auslese,95,66.0,Rheingau,NaN,NaN,tasters,NaN,Weingut Hans Bausch 2011 Hattenheimer Hassel A...,Riesling,Weingut Hans Bausch
464,Germany,"Richly textured and unabashedly full in body, ...",Westhofen Morstein GG Trocken,92,115.0,Rheinhessen,NaN,NaN,tasters,NaN,Wittmann 2011 Westhofen Morstein GG Trocken Ri...,Riesling,Wittmann
1457,Germany,Initial whiffs of smoke and struck flint fade ...,Brauneberg Juffer Sonnenuhr Trocken GG,94,56.0,Mosel,NaN,NaN,tasters,NaN,Fritz Haag 2015 Brauneberg Juffer Sonnenuhr Tr...,Riesling,Fritz Haag
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64189,Germany,Starts off with some intriguing notes of musk ...,Trockenbeerenauslese - 375 ml,90,350.0,Rheingau,NaN,NaN,tasters,@JoeCz,Schloss Vollrads 2007 Trockenbeerenauslese - 3...,Riesling,Schloss Vollrads
64261,Germany,"Befitting the historic nature of the estate, t...",Herrenberg Auslese #49,91,83.0,Mosel-Saar-Ruwer,NaN,NaN,tasters,@JoeCz,Maximin Grünhäuser 2006 Herrenberg Auslese #49...,Riesling,Maximin Grünhäuser
64278,Germany,"Smoke and petrol notes lead off, followed up b...",Hochheimer Domdechaney Erstes Gewächs,91,55.0,Rheingau,NaN,NaN,tasters,@JoeCz,Domdechant Werner 2006 Hochheimer Domdechaney ...,Riesling,Domdechant Werner
64324,Germany,"Dusty, smoky earth tones fade to reveal a rich...",Brauneberger Juffer Sonnenuhr Auslese Goldkapsel,92,52.0,Mosel,NaN,NaN,tasters,NaN,Fritz Haag 2013 Brauneberger Juffer Sonnenuhr ...,Riesling,Fritz Haag
64345,Germany,Fresh apple and white floral aromas are dusted...,Silberlack Trocken GG,91,75.0,Rheingau,NaN,NaN,tasters,NaN,Schloss Johannisberger 2012 Silberlack Trocken...,Riesling,Schloss Johannisberger

7. Conditional Selection (isin)
Filter the reviews DataFrame to show only wines from the provinces 'Sicily & Sardinia' OR 'Tuscany'.

In [27]:
taster_csv.loc[taster_csv.province.isin(['Sicily & Sardinia', 'Tuscany'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,tasters,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,tasters,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,tasters,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,tasters,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,tasters,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65466,Italy,"Earthy truffle, porcini mushroom, herb and gam...",NaN,88,70.0,Tuscany,Brunello di Montalcino,NaN,tasters,@kerinokeefe,Uccelliera 2012 Brunello di Montalcino,Sangiovese,Uccelliera
65474,Italy,"Made of 70% Syrah, 15% Sangiovese and 15% Merl...",Taneto,88,25.0,Tuscany,Toscana,NaN,tasters,@kerinokeefe,Badia di Morrona 2013 Taneto Red (Toscana),Red Blend,Badia di Morrona
65476,Italy,"Rose, violet, sour berry and tilled earth arom...",Prugnolo,88,25.0,Tuscany,Rosso di Montepulciano,NaN,tasters,@kerinokeefe,Boscarelli 2015 Prugnolo (Rosso di Montepulci...,Red Blend,Boscarelli
65477,Italy,"Made of 65% Merlot, 25% Cabernet Sauvignon, 5%...",Ruit Hora,88,30.0,Tuscany,Bolgheri,NaN,tasters,@kerinokeefe,Caccia al Piano 1868 2013 Ruit Hora (Bolgheri),Red Blend,Caccia al Piano 1868
65478,Italy,"Aromas suggesting French oak, coconut and spic...",NaN,88,36.0,Tuscany,Vino Nobile di Montepulciano,NaN,tasters,@kerinokeefe,Il Macchione 2012 Vino Nobile di Montepulciano,Sangiovese,Il Macchione

8. Handling Missing Data (isnull)
Filter the reviews DataFrame to show only wines where the designation column is missing (i.e., NaN). Save this filtered DataFrame to a variable called no_designation.

In [ ]:
no_designation = taster_csv.loc[taster_csv.designation.isnull()]

Empty DataFrame
Columns: [country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery, tax, country_winery]
Index: []

9. Assigning a New Column (Math)
Add a new column to reviews called tax. The values in this column should be the price multiplied by 1.2 (adding 20% tax).

In [62]:
Math = taster_csv['tax'] = taster_csv.price * 1.2
print(Math)

0         NaN
1        18.0
2         NaN
3        15.6
4        78.0
         ...
65494    54.0
65495     NaN
65496    24.0
65497    37.2
65498    12.0
Name: price, Length: 65499, dtype: float64

10. Assigning a New Column (Strings)
Add a new column to reviews called country_winery. The values should combine the country and the winery columns separated by a hyphen (e.g., 'Italy - Nicosia').

In [72]:
Strings = taster_csv['country_winery'] = taster_csv['country'] + "-" + taster_csv['winery']
print(Strings)

0                        Italy-Nicosia
1         Portugal-Quinta dos Avidagos
2        no_designation-no_designation
3                        US-St. Julian
4                      US-Sweet Cheeks
                     ...
65494             France-William Fèvre
65495    no_designation-no_designation
65496                         US-Fritz
65497                        US-Hendry
65498     Spain-Bodegas Dios Baco S.L.
Length: 65499, dtype: object